#!/usr/bin/python3

'''
AtxMon client.

Usage:
  atxmonc [options]

Options:
  -h, --help      Help.
  --log-level DEBUG | INFO | WARNING | ERROR
                  Debug level [default: INFO].
  -c <config_fn>  Config file path.
  -s <state_fn>   State file path.
  --host=<host>   Hostname to report.
  -u, --url=<url>
                  URL of AtxMon server.
'''

from atxmon.version import __version__

import os
import sys
import docopt
import atxmon
from atxmon.cfg import cfg

import logging
sys.excepthook = lambda t, v, tb: logging.critical('unhandled exception', exc_info=(t, v, tb))


def main():
	args = docopt.docopt(__doc__, version=__version__)
	log_level = args['--log-level']
	log_fn = 'atxmonc.log' if sys.platform == 'win32' else None
	atxmon.logging_setup(log_level, log_fn)
	logging.info('*' * 40)
	logging.info('starting atxmonc v%s' % __version__)
	logging.debug('args: %s' % dict(args))

	cfg_fn = args['-c']
	if not cfg_fn:
		for fn in (os.path.expanduser('~/.atxmonc/atxmonc.conf'), 'atxmonc.ini', '/etc/atxmonc/atxmonc.conf'):
			if not os.path.isfile(fn):
				continue
			cfg_fn = fn
			break

	if cfg_fn and not os.path.isfile(cfg_fn):
		logging.critical('%s does not exist, exiting' % cfg_fn)
		return

	if cfg_fn:
		logging.info('reading configuration from %s' % cfg_fn)
		cfg.read_from_ini(cfg_fn)
	else:
		logging.info('no configuration file specified nor found')

	state_fn = 'state.json'
	'''
	state_fn = args['-s']
	if not state_fn:
		for fn in (os.path.expanduser('~/.atxmonc/state.json'), 'state.json', '/var/lib/atxmonc/state.json'):
			if not os.path.isfile(fn): continue
			state_fn = fn
			break
	'''

	probes_fn = None
	if not probes_fn:
		for fn in (os.path.expanduser('~/.atxmonc/probes.conf'), 'probes.conf', '/etc/atxmonc/probes.conf'):
			if not os.path.isfile(fn):
				continue
			probes_fn = fn
			break

	if probes_fn and not os.path.isfile(probes_fn):
		logging.critical('%s does not exist, exiting' % probes_fn)
		return

	if not probes_fn:
		logging.critical('no configuration file specified nor found')
		return

	if args['--host']:
		cfg.host = args['--host']
	#if args['--interval']:
	#	cfg.interval = float(args['--interval'])
	if args['--url']:
		cfg.url = args['--url']

	err = cfg.check()
	if err:
		logging.critical(err)
		return

	logging.info('cfg: %s' % cfg)

	try:
		atxmon.run(cfg.url, probes_fn, cfg.host, state_fn)
	except KeyboardInterrupt:
		logging.debug('keyboard interrupt!')

	logging.info('exit')


if __name__ == '__main__':
	main()
