#!/usr/bin/python3

'''
AtxMon client.

Usage:
  atxmonc [options]

Options:
  -h, --help      Help.
  --log-level DEBUG | INFO | WARNING | ERROR
                  Debug level [default: INFO].
  -c <config_fn>  Config file path.
  --host=<host>   Hostname to report.
  -u, --url=<url>
                  URL of AtxMon server.
'''

__version__ = '0.0'

import os
import sys
import docopt
import atxmon
from atxmon.cfg import cfg

import logging
sys.excepthook = lambda t, v, tb: logging.critical('unhandled exception', exc_info=(t, v, tb))

def main():
	args = docopt.docopt(__doc__, version=__version__)

	log_level = args['--log-level']

	if sys.platform == 'win32':
		log_fn = 'faddnsc.log'
	else:
		log_fn = None
	#endif

	atxmon.logging_setup(log_level, log_fn)

	logging.info('*' * 40)
	logging.info('starting atxmonc v%s' % __version__)

	logging.debug(str(args))

	cfg_fn = args['-c']
	if not cfg_fn:
		for fn in (os.path.expanduser('~/.atxmonc.conf'), 'atxmonc.ini', '/etc/atxmonc.conf'):
			if not os.path.isfile(fn): continue
			cfg_fn = fn
			break
		#endfor
	#endif

	if cfg_fn and not os.path.isfile(cfg_fn):
		logging.critical('%s does not exist, exitting' % cfg_fn)
		return
	#endif

	if cfg_fn:
		logging.info('reading configuration from %s' % cfg_fn)
		cfg.read_from_ini(cfg_fn)
	else:
		logging.info('no configuration file specified nor found')
	#endif

	if args['--host']: cfg.host = args['--host']
	#if args['--interval']: cfg.interval = float(args['--interval'])
	if args['--url']: cfg.url = args['--url']

	err = cfg.check()
	if err:
		logging.critical(err)
		return
	#endif

	logging.info('%s' % cfg)

	try:
		atxmon.run()
	except KeyboardInterrupt:
		logging.debug('keyboard interrupt!')
	#endtry

	logging.info('exit')
#enddef


if __name__ == '__main__':
	main()
#endif
